export const DIALOG_LIST_FETCH = 'DIALOG_LIST_FETCH';
export const DIALOG_LIST_FETCHED_SUCCESS = 'DIALOG_LIST_FETCHED_SUCCESS';
export const DIALOG_LIST_FETCHED_FAILED = 'DIALOG_LIST_FETCHED_FAILED';

export const DIALOG_DETAIL_FETCH = 'DIALOG_DETAIL_FETCH';
export const DIALOG_DETAIL_FETCHED_SUCCESS = 'DIALOG_DETAIL_FETCHED_SUCCESS';
export const DIALOG_DETAIL_FETCHED_FAILED = 'DIALOG_DETAIL_FETCHED_FAILED';
