export const DIALOG_LIST_FETCH = 'DIALOG_LIST_FETCH';
export const DIALOG_LIST_FETCHED_SUCCESS = 'DIALOG_LIST_FETCHED_SUCCESS';
export const DIALOG_LIST_FETCHED_FAILED = 'DIALOG_LIST_FETCHED_FAILED';

export const DIALOG_DETAIL_FETCH = 'DIALOG_DETAIL_FETCH';
export const DIALOG_DETAIL_FETCHED_SUCCESS = 'DIALOG_DETAIL_FETCHED_SUCCESS';
export const DIALOG_DETAIL_FETCHED_FAILED = 'DIALOG_DETAIL_FETCHED_FAILED';

export const DIALOG_CREATE = 'DIALOG_CREATE';
export const DIALOG_CREATE_SUCCESS = 'DIALOG_CREATE_SUCCESS';
export const DIALOG_CREATE_FAILED = 'DIALOG_CREATE_FAILED';

export const MESSAGE_CREATE = 'MESSAGE_CREATE';
export const MESSAGE_CREATE_SUCCESS = 'MESSAGE_CREATE_SUCCESS';
export const MESSAGE_CREATE_FAILED = 'MESSAGE_CREATE_FAILED';
