export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';
export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';
export const USER_INFO_FETCH = 'USER_INFO_FETCH';
