export const USER_AUTHENTICATE = 'USER_AUTHENTICATE';
export const USER_AUTHENTICATED = 'USER_AUTHENTICATED';

export const USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';
export const USER_INFO_FETCH = 'USER_INFO_FETCH';

export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGNED_UP_SUCCESS = 'USER_SIGNED_UP_SUCCESS';
export const USER_SIGNED_UP_FAILED = 'USER_SIGNED_UP_FAILED';
