export const SCENARIO_LIST_FETCH = 'SCENARIO_LIST_FETCH';
export const SCENARIO_LIST_FETCHED_SUCCESS = 'SCENARIO_LIST_FETCHED_SUCCESS';
export const SCENARIO_LIST_FETCHED_FAILED = 'SCENARIO_LIST_FETCHED_FAILED';

export const SCENARIO_DETAIL_FETCH = 'SCENARIO_DETAIL_FETCH';
export const SCENARIO_DETAIL_FETCHED_SUCCESS =
  'SCENARIO_DETAIL_FETCHED_SUCCESS';
export const SCENARIO_DETAIL_FETCHED_FAILED = 'SCENARIO_DETAIL_FETCHED_FAILED';
